### ISSUE TITLE
Investigación y Análisis

### ISSUE THREAD

**Issue by EdissonGirald0** [Resuelve-IA/Soy-diferente-soy-BotPoli-#1]
- Investigación sobre las necesidades y preferencias de los estudiantes de politécnico Grancolombiano.

- Análisis de la competencia y los bots existentes en WhatsApp.

- Identificación de los requisitos del negocio y las funcionalidades clave del bot.

**Comment by EdissonGirald0** [comment]
en esta primera parte consignaremos las investigaciones realizadas para darle forma a el proyecto

**Comment by andresm9** [comment]
Creating a WhatsApp bot involves using a chatbot development platform and connecting it to your WhatsApp Business account. Here's a breakdown of the key steps:

1. **Platform Selection**: Choose a chatbot development platform that suits your needs. There are options with free plans or trials, like Landbot.

2. **WhatsApp Business Account**: You'll need a verified WhatsApp Business account to connect your bot. This involves a Facebook Business Manager account and a phone number for verification.

3. **Building the Bot**: The platform will provide tools to design your bot's conversation flow. You can define what questions it asks, what answers it provides, and how it responds to user input.

4. **Testing and Deployment**: Once you've built your bot, test it thoroughly within the platform before deploying it to your WhatsApp Business account.

Remember, this is a simplified overview. The specific steps might vary depending on the platform you choose.

**Comment by EdissonGirald0** [comment]
## Create a WhatsApp bot: alternatives and additional details

**It is true that creating a WhatsApp bot generally involves the steps mentioned:**

1. **Platform Selection:** Choose a chatbot development platform that fits your needs.
2. **WhatsApp Business Account:** Get a verified WhatsApp Business account.
3. **Creation of the bot:** Design the conversation flow of the bot on the chosen platform.
4. **Testing and deployment:** Test the bot and then deploy it to the WhatsApp Business account.

**However, there are other alternatives for each step:**

**1. Platforms:**

* **Bookstores:**
     * **Baileys:** Offers greater flexibility and control over the bot, but requires programming knowledge.
     * **WhatsappWeb:** Allows you to create simple bots without the need to program.

* **Online tools:**
     * **Chatfuel:** Intuitive and easy-to-use interface, ideal for beginners.
     * **ManyChat:** Powerful and with advanced options, such as integration with Facebook Messenger.

**2. WhatsApp Business account:**

* **Alternatives:**
     * **WhatsApp API:** Allows you to connect your bot to WhatsApp without the need for a Business account.
     * **Service Providers:** Some companies offer bot creation and management services that include the Business account.

**3. Bot creation:**

* **Conversational approach:**
     * **Branching Dialogs:** Design different responses based on the user's choices.
     * **Decision tree:** Structure the conversation flow in a logical and hierarchical way.

* **Tool Integration:**
     * **Conversational AI:** Improve the naturalness and fluidity of the bot.
     * **Third-party APIs:** Add functionalities such as payments or reservations.

**4. Testing and implementation:**

* **Exhaustive tests:** Simulate different interaction scenarios with the bot.
* **Monitoring and analysis:** Measure bot performance and make adjustments.

**In summary:**

* There are various options to create a WhatsApp bot, from platforms with visual interfaces to libraries that require programming.
* Choosing the best alternative will depend on your needs, budget and technical skills.
* It is important to spend time planning, designing, testing and optimizing the bot to ensure its success.

**Additional resources:**

* **Bookstores:**
     * Baileys: [https://github.com/WhiskeySockets/Baileys](Link)
     * WhatsappWeb: [https://docs.mikrosystem.net/docs/whatsapp-web-api](Link)
* **Online tools:**
     * Chatfuel: [https://chatfuel.com/](https://chatfuel.com/)
     * ManyChat: [https://manychat.com/](https://manychat.com/)
* **Service providers:**
     * Dialogflow: [https://cloud.google.com/dialogflow/](https://cloud.google.com/dialogflow/)
     * Rasa: [https://rasa.com/](https://rasa.com/)
